[package]
name = "pmi-k8s"
version = "0.1.0"
edition = "2024"
default-run = "pmi-k8s"

[[bin]]
name = "mock"
required-features = ["test-bins"]

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros", "io-util", "process", "fs", "signal"] }
tokio-stream = { version = "0.1", features = ["net", "sync"] }
kube = { version = "4", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.28", features = ["latest"] }
thiserror = "2"
libc = "0.2"
nix = { version = "0.31", features = ["user", "hostname"] }
tempdir = { version = "0.3" }
tracing = "0.1"
# Entry-point dependencies
clap = { version = "4", features = ["derive"] }
anyhow = "1"
# Test dependencies
mpi = { version = "0.8", optional = true }
notify = { version = "8", optional = true }

[build-dependencies]
bindgen = "0.72"
pkg-config = "0.3"

[dev-dependencies]
serial_test = "4"

[features]
test-bins = ["dep:mpi", "dep:notify"]

[lints.clippy]
panic = "warn"
unwrap_used = "warn"
undocumented_unsafe_blocks = "warn"

[lints.rust]
# lib is for internal use only, so we don't care about stability
async_fn_in_trait = "allow"
